name: mkdocs-generation
on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.x
      - uses: actions/cache@main
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material[imaging]
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocstrings[python]
      - run: mkdocs gh-deploy --force